# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.23
# 
# >> macros
# << macros

Name:       desktop-file-utils
Summary:    Utilities for manipulating .desktop files
Version:    0.19
Release:    1
Group:      Development/Tools
License:    GPLv2+
URL:        http://www.freedesktop.org/software/desktop-file-utils
Source0:    http://www.freedesktop.org/software/desktop-file-utils/releases/%{name}-%{version}.tar.xz
Source100:  desktop-file-utils.yaml
BuildRequires:  pkgconfig(glib-2.0)


%description
.desktop files are used to describe an application for inclusion in
GNOME or KDE menus.  This package contains desktop-file-validate which
checks whether a .desktop file complies with the specification at
http://www.freedesktop.org/standards/, and desktop-file-install 
which installs a desktop file to the standard directory, optionally 
fixing it up in the process.




%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static
make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post






%files
%defattr(-,root,root,-)
# >> files
%doc AUTHORS COPYING README NEWS
%{_bindir}/*
%{_mandir}/man1/*.1.gz
# << files


